import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Blog.module.css";

interface MyProps {
  name: string;
}
export default function Blog(props: MyProps) {
  const { name } = props;
  // console.log(props);
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/">Go back</Link>
      <h1 className={styles.title}>Hola soy tu blog</h1>
      <h2>{name}</h2>
    </div>
  );
}

// esta funciona se ejecuta en el servidor y se lo envia al componente
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://localhost:3000/api/hello`);
  const data = await res.json();
  // console.log(data);

  // Pass data to the page via props
  return { props: { name: data.name } };
}
