import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js MaximoProg!</a>
        </h1>
      </main>
      <div className={styles.content}>
        <div className={styles.uncles}>
          <Link href="/Blog">My blog</Link>
        </div>
      </div>
    </div>
  );
};

export default Home;
